name: Generate GitHub Stats

on:
  schedule:
    - cron: "0 */12 * * *"  # runs every 12 hours
  workflow_dispatch:         # allows manual trigger
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3

      - name: Generate Stats Card
        uses: anuraghazra/github-readme-stats@master
        with:
          username: Amruth011
          theme: github_dark
          show_icons: true
          include_all_commits: true
          count_private: true
          hide_border: true
          bg_color: "0d1117"
          title_color: "58a6ff"
          icon_color: "58a6ff"
          text_color: "8b949e"
          output_path: github-stats.svg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate Top Languages Card
        uses: anuraghazra/github-readme-stats@master
        with:
          username: Amruth011
          card_type: top-langs
          theme: github_dark
          layout: compact
          langs_count: 8
          hide_border: true
          bg_color: "0d1117"
          title_color: "58a6ff"
          text_color: "8b949e"
          output_path: github-langs.svg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit generated SVGs
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add github-stats.svg github-langs.svg
          git diff --staged --quiet || git commit -m "chore: update github stats [skip ci]"
          git push
